# Generated by Django 4.0.7 on 2022-08-27 20:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_remove_user_email address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=ckeditor.fields.RichTextField(default='', max_length=255),
        ),
    ]
