# Generated by Django 4.0.7 on 2022-08-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(auto_created=True, default=7586)),
                ('user', models.TextField()),
            ],
        ),
    ]
