# Generated by Django 4.0.7 on 2022-08-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimecode',
            name='code',
            field=models.TextField(auto_created=True, default=1050),
        ),
    ]
