# Generated by Django 4.0.7 on 2022-08-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_alter_onetimecode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimecode',
            name='code',
            field=models.TextField(auto_created=True, default=6869),
        ),
    ]
