# Generated by Django 4.0.7 on 2022-08-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0005_alter_onetimecode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimecode',
            name='code',
            field=models.TextField(auto_created=True, default=7892),
        ),
    ]
